import sys

# from .generate import execute_from

sys.exit(TypeError('something bad happened'))
